name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
      - master
      - develop
    paths:
      - '**.go'
      - 'docs/**'
      - '.github/workflows/docs.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install pkgsite
        run: go install golang.org/x/pkgsite/cmd/pkgsite@latest

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Install OpenAPI generator
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Run go fmt
        run: go fmt ./...

      - name: Generate API documentation
        run: |
          mkdir -p docs/api
          cp docs/openapi.yaml docs/api/
          openapi-generator-cli generate -i docs/openapi.yaml -g html2 -o docs/api/html
          openapi-generator-cli generate -i docs/openapi.yaml -g markdown -o docs/api/markdown

      - name: Generate code documentation
        run: |
          mkdir -p docs/code
          TEMP_DIR=$(mktemp -d)
          cd ${TEMP_DIR}
          go mod init example.com/docs
          go get github.com/hromovyi-kostiantyn/product-recommendations-go@${GITHUB_SHA}
          mkdir -p site
          pkgsite -dir=site -open=false github.com/hromovyi-kostiantyn/product-recommendations-go
          cp -r site/* ../../docs/code/
          cd ../../

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Try v3 instead

  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3  # Updated to v3